apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds/full
  - shared-config
  - controller-manager
  - numaflow-server
  - dex

images:
  - name: quay.io/numaproj/numaflow
    newTag: v1.1.1

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: numaflow-controller
    spec:
      template:
        spec:
          containers:
            - name: controller-manager
              env:
                - name: NUMAFLOW_IMAGE
                  value: quay.io/numaproj/numaflow:v1.1.1
