kind: ConfigMap
apiVersion: v1
metadata:
  name: numaflow-dex-server
data:
  config.yaml: |
    issuer: https://localhost:8443/dex
    storage:
      type: memory
    web:
      http: 0.0.0.0:5556
    staticClients:
      - id: numaflow-server-app
        redirectURIs: 
          - https://localhost:8443/login
        name: 'Numaflow Server App'
        public: true
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: https://localhost:8443/dex/callback
        orgs:
        - name: numa-default-dex-auth
          teams:
          - admin
          - readonly
    oauth2:
      skipApprovalScreen: true
