apiVersion: apps/v1
kind: Deployment
metadata:
  name: numaflow-dex-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: numaflow-dex-server
      app.kubernetes.io/part-of: numaflow
      app.kubernetes.io/component: dex-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: numaflow-dex-server
        app.kubernetes.io/part-of: numaflow
        app.kubernetes.io/component: dex-server
    spec:
      serviceAccountName: numaflow-dex-server
      initContainers:
      - name: dex-init
        image: quay.io/numaproj/numaflow:latest
        imagePullPolicy: Always
        args:
        - dex-server-init
        volumeMounts:
        - mountPath: /cfg
          name: connector-config
        - mountPath: /tls
          name: tls
        - mountPath: /tmp
          name: generated-dex-config
        env:
        - name: NUMAFLOW_SERVER_DEX_TLS
          valueFrom:
            configMapKeyRef:
              name: numaflow-cmd-params-config
              key: server.dex.disable.tls
              optional: true
        - name: NUMAFLOW_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: numaflow-cmd-params-config
              key: server.address
              optional: true
      containers:
        - name: dex
          image: dexidp/dex:v2.37.0
          imagePullPolicy: Always
          command: ["/usr/local/bin/dex", "serve", "/etc/numaflow/dex/cfg/config.yaml"]
          ports:
            - containerPort: 5556
          volumeMounts:
            - mountPath: /etc/numaflow/dex/cfg/config.yaml
              name: generated-dex-config
              subPath: config.yaml
            - mountPath: /etc/numaflow/dex/tls/tls.crt
              name: tls
              subPath: tls.crt
            - mountPath: /etc/numaflow/dex/tls/tls.key
              name: tls
              subPath: tls.key
          env:
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: numaflow-dex-secrets
                  key: dex-github-client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: numaflow-dex-secrets
                  key: dex-github-client-secret
      volumes:
        - name: connector-config
          configMap:
            name: numaflow-dex-server-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: tls
          emptyDir: {}
        - name: generated-dex-config
          emptyDir: {}
