site_name: Numaflow - Data/streaming processing platform on Kubernetes
repo_url: https://github.com/numaproj/numaflow
edit_uri: edit/main/docs/
strict: true
theme:
  name: material
  favicon: assets/numaproj.svg
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
extra:
  analytics:
    provider: google
    property: G-M7DD40E8RV
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
nav:
  - Home: README.md
  - Getting Started:
      - quick-start.md
  - User Guide:
      - Core Concepts:
          - user-guide/pipeline.md
          - user-guide/vertex.md
          - user-guide/inter-step-buffer.md
          - user-guide/inter-step-buffer-service.md
      - Sources:
          - user-guide/sources/generator.md
          - user-guide/sources/http.md
          - user-guide/sources/kafka.md
      - Sinks:
          - user-guide/sinks/kafka.md
          - user-guide/sinks/log.md
          - user-guide/sinks/blackhole.md
          - User Defined Sinks: "user-guide/sinks/user-defined-sinks.md"
      - User Defined Functions:
          - Overview: "user-guide/user-defined-functions.md"
          - Built-in UDFs:
              - Overview: "user-guide/builtin-functions/README.md"
              - Cat: "user-guide/builtin-functions/cat.md"
              - Filter: "user-guide/builtin-functions/filter.md"
      - user-guide/pipeline-tuning.md
      - user-guide/conditional-forwarding.md
      - user-guide/autoscaling.md
      - user-guide/container-resources.md
      - user-guide/volumes.md
      - user-guide/environment-variables.md
      - user-guide/init-containers.md
      - user-guide/sidecar-containers.md
      - user-guide/pipeline-customization.md
      - user-guide/watermarks.md
      - APIs.md
  - Operator Manual:
      - Releases â§‰: "operations/releases.md"
      - operations/installation.md
      - Configuration:
          - Controller Configuration: "operations/controller-configmap.md"
          - operations/metrics/metrics.md
          - operations/grafana.md
  - Developer Guide:
      - development/development.md
      - Specifications:
          - Overview: "specifications/overview.md"
          - "specifications/autoscaling.md"
      - development/debugging.md
      - development/static-code-analysis.md
      - development/releasing.md
  - Numaproj: https://numaproj.io
