apiVersion: apps/v1
kind: Deployment
metadata:
  name: numaflow-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: controller-manager
      app.kubernetes.io/part-of: numaflow
      app.kubernetes.io/component: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: controller-manager
        app.kubernetes.io/part-of: numaflow
        app.kubernetes.io/component: controller-manager
    spec:
      serviceAccountName: numaflow-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 9737
      containers:
        - name: controller-manager
          image: quay.io/numaproj/numaflow:latest
          imagePullPolicy: Always
          args:
            - controller
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NUMAFLOW_IMAGE
              value: quay.io/numaproj/numaflow:latest
            - name: NUMAFLOW_CONTROLLER_NAMESPACED
              valueFrom:
                configMapKeyRef:
                  name: numaflow-cmd-params-config
                  key: namespaced
                  optional: true
            - name: NUMAFLOW_CONTROLLER_MANAGED_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: numaflow-cmd-params-config
                  key: managed.namespace
                  optional: true
            - name: NUMAFLOW_LEADER_ELECTION_DISABLED
              valueFrom:
                configMapKeyRef:
                  name: numaflow-cmd-params-config
                  key: controller.disable.leader.election
                  optional: true
          volumeMounts:
            - mountPath: /etc/numaflow
              name: controller-config-volume
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 200Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: controller-config-volume
          configMap:
            name: numaflow-controller-config
