[package]
name = "numaflow-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing.workspace = true
tonic.workspace = true
tokio.workspace = true
numaflow-pb.workspace = true
rcgen.workspace = true
time.workspace = true

[lints]
workspace = true
