#
# Controller only with namespaced install, witout CRD
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/shared-config
  - ../../base/controller-manager
  - ../../namespace-install/rbac/controller-manager

images:
  - name: quay.io/numaproj/numaflow
    newTag: v1.2.0-rc3

patchesStrategicMerge:
  # For release scripts
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: numaflow-controller
    spec:
      template:
        spec:
          containers:
            - name: controller-manager
              env:
                - name: NUMAFLOW_IMAGE
                  value: quay.io/numaproj/numaflow:v1.2.0-rc3
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: numaflow-cmd-params-config
    data:
      namespaced: "true"
