[package]
name = "backoff"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
tokio = {workspace = true, features = ["time"]}
pin-project.workspace = true
rand.workspace = true
