apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: numaflow-server-secrets-binding
  labels:
    app.kubernetes.io/name: numaflow-ux
    app.kubernetes.io/part-of: numaflow
    app.kubernetes.io/component: numaflow-ux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: numaflow-server-secrets-role
subjects:
  - kind: ServiceAccount
    name: numaflow-server-sa
