apiVersion: v1
kind: ConfigMap
metadata:
  name: numaflow-cmd-params-config
data:
  ### Whether to run the controller and the UX server in namespaced scope, defaults to false.
  # namespaced: "false"
  #
  ### The namespace that the controller and the UX server watch when "namespaced" is true.
  # managed.namespace: numaflow-system
  #
  ### Whether to disable leader election for the controller, defaults to false
  # controller.leader.election.disabled: "false"
  #
  ### The duration that non-leader candidates will wait to force acquire leadership. 
  #   This is measured against time of last observed ack. Default is 15 seconds.
  #   The configuration has to be: lease.duration > lease.renew.deadline > lease.renew.period
  # controller.leader.election.lease.duration: 15s
  #
  ### The duration that the acting controlplane will retry refreshing leadership before giving up. 
  #   Default is 10 seconds.
  #   The configuration has to be: lease.duration > lease.renew.deadline > lease.renew.period
  # controller.leader.election.lease.renew.deadline: 10s
  #
  ### The duration the LeaderElector clients should wait between tries of actions, which means every
  #   this period of time, it tries to renew the lease. Default is 2 seconds.
  #   The configuration has to be: lease.duration > lease.renew.deadline > lease.renew.period
  # controller.leader.election.lease.renew.period: 2s
  #
  ### Whether to disable TLS for UX server.
  # server.insecure: "false"
  #
  ### Port to listen on for UX server, defaults to 8443 or 8080 if insecure is set.
  # server.port: "8443"
  #
  ### Base href for Numaflow UX server, defaults to '/'.
  # server.base.href: "/"
  #
  ### Whether to enable read only view for the UX server, defaults to false.
  #  server.readonly: "false"
  #
  ### Whether to disable authentication and authorization for the UX server, defaults to false.
  server.disable.auth: "true"
  #
  ### The external address of the Numaflow server. This is needed when using Dex for authentication.
  # server.address: https://localhost:8443
