apiVersion: v1
kind: ConfigMap
metadata:
  name: numaflow-cmd-params-config
data:
  ### Whether to run the controller and the UX server in namespaced scope, defaults to false.
  # namespaced: "false"
  #
  ### The namespace that the controller and the UX server watch when "namespaced" is true.
  # managed.namespace: numaflow-system
  #
  ### Whether to disable leader election for the controller, defaults to false
  # controller.disable.leader.election: "false"
  #
  ### Whether to disable TLS for UX server.
  # server.insecure: "false"
  #
  ### Port to listen on for UX server, defaults to 8443 or 8080 if insecure is set.
  # server.port: "8443"
  #
  ### Base href for Numaflow UX server, defaults to '/'.
  # server.base.href: "/"
  #
  ### Whether to disable authentication and authorization for the UX server, defaults to false.
  server.disable.auth: "true"
  #
  ### The external address of the Numaflow server. This is needed when using Dex for authentication.
  # server.address: https://localhost:8443
  #
  # The list of allowed origins for CORS on numaflow api
  # server.cors.allowed.origins: https://localhost:8443, https://localhost:8444
