#
# Controller only with namespaced install, without CRD
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/shared-config
  - ../../base/numaflow-server
  - ../../namespace-install/rbac/numaflow-server

images:
  - name: quay.io/numaproj/numaflow
    newTag: v1.1.3

patchesStrategicMerge:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: numaflow-cmd-params-config
    data:
      namespaced: "true"

