apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - numaflow-server-sa.yaml
  - numaflow-server-rbac-config.yaml
  - numaflow-server-deployment.yaml
  - numaflow-server-service.yaml
  - numaflow-server-local-user-config.yaml
  - numaflow-server-secrets.yaml
  - numaflow-metric-server-config.yaml