apiVersion: apps/v1
kind: Deployment
metadata:
  name: numaflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: numaflow-ux
      app.kubernetes.io/part-of: numaflow
      app.kubernetes.io/component: numaflow-ux
  template:
    metadata:
      labels:
        app.kubernetes.io/name: numaflow-ux
        app.kubernetes.io/part-of: numaflow
        app.kubernetes.io/component: numaflow-ux
    spec:
      serviceAccountName: numaflow-server-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 9737
      volumes:
      - name: env-volume
        emptyDir: {}
      - name: rbac-config
        configMap:
          name: numaflow-server-rbac-config
      initContainers:
      - name: server-init
        image: quay.io/numaproj/numaflow:latest
        args:
        - "server-init"
        imagePullPolicy: Always
        env:
        - name: NUMAFLOW_SERVER_BASE_HREF
          valueFrom:
            configMapKeyRef:
              name: numaflow-cmd-params-config
              key: server.base.href
              optional: true
        volumeMounts:
        - mountPath: /opt/numaflow
          name: env-volume
      - name: server-secrets-init
        image: quay.io/numaproj/numaflow:latest
        args:
        - "server-secrets-init"
        imagePullPolicy: Always
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      containers:
        - name: main
          image: quay.io/numaproj/numaflow:latest
          args:
          - "server"
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /ui/build/runtime-env.js
            name: env-volume
            subPath: runtime-env.js
          - mountPath: /ui/build/index.html
            name: env-volume
            subPath: index.html
          - mountPath: /etc/numaflow
            name: rbac-config
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NUMAFLOW_SERVER_INSECURE
            valueFrom:
              configMapKeyRef:
                name: numaflow-cmd-params-config
                key: server.insecure
                optional: true
          - name: NUMAFLOW_SERVER_PORT_NUMBER
            valueFrom:
              configMapKeyRef:
                name: numaflow-cmd-params-config
                key: server.port
                optional: true
          - name: NUMAFLOW_SERVER_NAMESPACED
            valueFrom:
              configMapKeyRef:
                name: numaflow-cmd-params-config
                key: namespaced
                optional: true
          - name: NUMAFLOW_SERVER_MANAGED_NAMESPACE
            valueFrom:
              configMapKeyRef:
                name: numaflow-cmd-params-config
                key: managed.namespace
                optional: true
          - name: NUMAFLOW_SERVER_BASE_HREF
            valueFrom:
              configMapKeyRef:
                name: numaflow-cmd-params-config
                key: server.base.href
                optional: true
          - name: NUMAFLOW_SERVER_DISABLE_AUTH
            valueFrom:
              configMapKeyRef:
                name: numaflow-cmd-params-config
                key: server.disable.auth
                optional: true
          - name: NUMAFLOW_SERVER_DEX_SERVER_ADDR
            valueFrom:
              configMapKeyRef:
                name: numaflow-cmd-params-config
                key: server.dex.server
                optional: true
          - name: NUMAFLOW_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: numaflow-cmd-params-config
                key: server.address
                optional: true
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 200Mi
          livenessProbe:
            httpGet:
              path: /livez
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 3
            periodSeconds: 3
